---
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker if not present
  ansible.builtin.package:
    name: docker.io
    state: present

- name: Pull Docker Image
  docker_image:
    name: ireneromero95/vote
    source: pull
    tag: latest

- name: Run Container
  docker_container:
    name: client
    image: ireneromero95/client:latest # Change!
    ports:
      - '80:80' # port mappings
    state: started
