---
# - name: Update apt package index
#   ansible.builtin.apt:
#     update_cache: yes

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

# - name: Install Docker if not present
#   ansible.builtin.package:
#     name: docker.io
#     state: present

- name: Prepare all instances with Docker
  hosts: all
  become: yes
  tasks:
    - name: Update apt and install Docker
      apt:
        name:
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

#Database
- name: Deploy PostgreSQL
  hosts: database
  become: yes
  tasks:
    - name: Run Postgres Container
      docker_container:
        name: db
        image: postgres:15-alpine
        state: started
        restart_policy: always

# - name: Pull Docker Image
#   docker_image:
#     name: ireneromero95/vote
#     source: pull
#     tag: latest

# - name: Run Container
#   docker_container:
#     name: client
#     image: ireneromero95/client:latest # Change!
#     ports:
#       - '80:80' # port mappings
#     state: started

#Backend

- name: Deploy Backend Services
  hosts: backend
  become: yes
  tasks:
    - name: Run Redis Container
      docker_container:
        name: redis
        image: redis:alpine
        state: started
        ports:
          - '6379:6379'

    - name: Run Worker Container (.NET)
      docker_container:
        name: worker
        image: your-dockerhub/worker:latest
        state: started
        env:
          REDIS_HOST: 'localhost' # Same instance
          DB_HOST: "{{ hostvars['db_instance']['ansible_host'] }}"

#Frontend
- name: Deploy Frontend Services
  hosts: frontend
  become: yes
  tasks:
    - name: Run Vote App (Python)
      docker_container:
        name: vote
        image: your-dockerhub/vote:latest
        state: started
        ports:
          - '5000:80'
        env:
          REDIS_HOST: "{{ hostvars['backend_instance']['ansible_host'] }}"

    - name: Run Result App (Node.js)
      docker_container:
        name: result
        image: your-dockerhub/result:latest
        state: started
        ports:
          - '4000:80'
        env:
          DB_HOST: "{{ hostvars['db_instance']['ansible_host'] }}"
