- name: Prepare all instances with Docker
  hosts: all
  become: true
  tasks:
    - name: Update apt and install Docker
      apt:
        name:
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

#Database
- name: Deploy PostgreSQL
  hosts: database
  become: true
  tasks:
    - name: Run Postgres Container
      docker_container:
        name: db
        image: postgres:15-alpine
        state: started
        restart_policy: always

#Backend

- name: Deploy Backend Services
  hosts: backend
  become: true
  tasks:
    - name: Run Redis Container
      docker_container:
        name: redis
        image: redis:alpine
        state: started
        ports:
          - '6379:6379'

    - name: Run Worker Container (.NET)
      docker_container:
        name: worker
        image: your-dockerhub/worker:latest
        state: started
        env:
          REDIS_HOST: 'localhost' # Same instance
          DB_HOST: "{{ hostvars['database-1']['ansible_host'] }}"

#Frontend
- name: Deploy Frontend Services
  hosts: frontend
  become: true
  tasks:
    - name: Run Vote App (Python)
      docker_container:
        name: vote
        image: your-dockerhub/vote:latest
        state: started
        ports:
          - '5000:80'
        env:
          REDIS_HOST: "{{ hostvars['backend_instance']['ansible_host'] }}"

    - name: Run Result App (Node.js)
      docker_container:
        name: result
        image: your-dockerhub/result:latest
        state: started
        ports:
          - '4000:80'
        env:
          DB_HOST: "{{ hostvars['database-1']['ansible_host'] }}"
